### ISSUE TITLE
deployment workflow detailed on site currently not configured for key

### ISSUE THREAD

**Issue by alisterburt** [pydev-guide/pydev-guide.github.io#21]
Hey! The current deployment workflow with the action https://github.com/pypa/gh-action-pypi-publish tries to used the trusted publisher flow - for existing projects this works great but configuring it requires that the project already exist on PyPI... for a brand new project you first need to deploy (and therefore setup keys etc)

You can add a block to specify the key in the action like this
```yaml
  with:
    password: ${{ secrets.TWINE_API_KEY }}
```

What do you think is the best path forward here, raise the issue to the pypi guys or just go back to using/configuring keys?

found with @LorenzLamm while deploying a new project

**Comment by tlambert03** [comment]
> for existing projects this works great but configuring it requires that the project already exist on PyPI... for a brand new project you first need to deploy (and therefore setup keys etc)

have you already seen and ruled out the “pending project” feature on pypi?

https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/

https://pypi.org/manage/account/publishing/

**Comment by alisterburt** [comment]
magic!! didn't find this whilst trying to figure it out - thanks a bunch!

**Comment by tlambert03** [comment]
If a quick note to that effect would have clarified things here, let me know where it would have helped

**Comment by alisterburt** [comment]
Replacing this part of the quickstart guide

https://github.com/pydev-guide/pydev-guide.github.io/blob/e36e804d6c73fe60b1092f188f028d1094c08f7b/docs/quickstart.md?plain=1#L354-L364

with something along the lines of

````md
Your project has been configured for automated deployments using [gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) in the *deploy* section of `ci.yml`

```yaml
      - name: 🚢 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```

For deployment to succeed, you first need to configure the project on PyPI so that it expects a deployment from this GitHub account and repository.
- [instructions for configuring a new project](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/)
- [instructions for configuring an existing project](https://docs.pypi.org/trusted-publishers/adding-a-publisher/)
````

Would be wonderful, if you agree happy to PR otherwise please edit and include as you see fit :-)
