### ISSUE TITLE
Key bindings for navigation

### ISSUE THREAD

**Issue by jdeschamps** [pydev-guide/pydev-guide.github.io#3]
Hi!

I suppose from [that section](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#keyboard-shortcuts) that the "P" and "N" navigation are the defaults. Not a big deal, but I find them a bit annoying due to their place on the keyboard.

Do you think it would make sense to use "A" and "D" instead? 

(although that would be f*cking with the French)

**Comment by tlambert03** [comment]
You can also use . and , ... but those didn't look as apparent on the keys :) 

https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#mode:global

We can add additional keys probably, but would prefer not to since those are built in

**Comment by tlambert03** [comment]
Oh sorry you had the same link 😅

**Comment by jdeschamps** [comment]
Okay, then let's make a mental note and not mess with the defaults key bindings right now. :)
